# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://192.168.100.100:4000/
title: Kodokuman blog
author: johna1203

twitter: johna1203
facebook: johnathan.david

projects :
 - name: Magedox
   url : http://johna1203.github.io/Magedox
 - name: Delifi
   url : https://github.com/Kodokux/Mage-Delifi
 - name: Kodokux-debug
   url : https://github.com/Kodokux/kodokux-debug


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Analytics
#google_analytics_tracking_id: UA-XXXXXXXX-X