# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://192.168.100.100:4000/
title: Kodokuman blog
author: johna1203

twitter: johna1203
facebook: johnathan.david
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Analytics
#google_analytics_tracking_id: UA-XXXXXXXX-X