# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://johna1203.github.io/
title: Kodokuman blog
author: johna1203

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Analytics
#google_analytics_tracking_id: UA-XXXXXXXX-X